from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path
from typing import Any


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            rows.append(json.loads(line))
    return rows


def write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(json.dumps(row, ensure_ascii=False) for row in rows) + ("\n" if rows else ""), encoding="utf-8")


def canonical_rows(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [row for row in rows if row.get("status") == "accepted"]


def llm_rows(rows: list[dict[str, Any]], language: str) -> list[dict[str, Any]]:
    zh = language == "zh"
    instruction = (
        "请从输入文本中抽取实体、关系和属性，并按给定 JSON 结构输出。"
        if zh
        else "Extract entities, relations, and attributes from the input text and return the specified JSON structure."
    )
    output_rows = []
    for row in rows:
        output_rows.append(
            {
                "messages": [
                    {"role": "system", "content": instruction},
                    {"role": "user", "content": row.get("text", "")},
                    {
                        "role": "assistant",
                        "content": json.dumps(
                            {
                                "entities": row.get("entities", []),
                                "relations": row.get("relations", []),
                                "attributes": row.get("attributes", []),
                            },
                            ensure_ascii=False,
                        ),
                    },
                ],
                "source": row.get("source", {}),
                "id": row.get("id"),
            }
        )
    return output_rows


def relation_rows(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    output_rows = []
    for row in rows:
        entities = {entity.get("id", ""): entity for entity in row.get("entities", [])}
        for relation in row.get("relations", []):
            subject = entities.get(relation.get("subject", ""), {})
            obj = entities.get(relation.get("object", ""), {})
            output_rows.append(
                {
                    "id": f"{row.get('id')}-{relation.get('subject')}-{relation.get('predicate')}-{relation.get('object')}",
                    "text": row.get("text", ""),
                    "subject": subject,
                    "predicate": relation.get("predicate"),
                    "object": obj,
                    "confidence": relation.get("confidence"),
                    "source": row.get("source", {}),
                }
            )
    return output_rows


def ner_char_rows(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    output_rows = []
    for row in rows:
        text = row.get("text", "")
        spans = []
        for entity in row.get("entities", []):
            start = entity.get("start")
            end = entity.get("end")
            if isinstance(start, int) and isinstance(end, int) and 0 <= start < end <= len(text):
                spans.append(
                    {
                        "start": start,
                        "end": end,
                        "text": entity.get("text", text[start:end]),
                        "label": entity.get("class"),
                        "confidence": entity.get("confidence"),
                    }
                )
        output_rows.append({"id": row.get("id"), "text": text, "spans": spans, "source": row.get("source", {})})
    return output_rows


def write_readme(output_dir: Path, counts: dict[str, int], language: str) -> None:
    if language == "zh":
        text = f"""# 训练数据导出

本目录由 `export_training_data.py` 生成。

## 文件

- `canonical_accepted.jsonl`: 人工审核通过后的规范标注数据，作为源数据。
- `llm_finetune.jsonl`: 面向 LLM 指令微调的 messages 格式。
- `relation_extraction.jsonl`: 面向关系抽取任务的三元组样本。
- `ner_spans.jsonl`: 面向 NER/BERT 转换的 span 样本，可继续转换为 BIO/BILOU。

## 数量

- accepted examples: {counts['accepted']}
- relation examples: {counts['relations']}
- ner examples: {counts['ner']}

待审核和拒绝数据不会自动进入训练数据。请先处理 `pending_review.jsonl` 和 `rejected_or_negative.jsonl`。
"""
    else:
        text = f"""# Training Data Export

Generated by `export_training_data.py`.

## Files

- `canonical_accepted.jsonl`: reviewed canonical annotation data.
- `llm_finetune.jsonl`: messages format for LLM fine-tuning.
- `relation_extraction.jsonl`: triple-style relation extraction examples.
- `ner_spans.jsonl`: span examples for NER/BERT conversion to BIO/BILOU.

## Counts

- accepted examples: {counts['accepted']}
- relation examples: {counts['relations']}
- ner examples: {counts['ner']}

Pending and rejected data are not automatically used for training.
"""
    (output_dir / "README.md").write_text(text, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Export reviewed ontology-guided annotations into training-data formats.")
    parser.add_argument("--accepted", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--language", choices=["zh", "en"], default="zh")
    args = parser.parse_args()

    rows = canonical_rows(load_jsonl(args.accepted))
    args.output_dir.mkdir(parents=True, exist_ok=True)

    canonical_path = args.output_dir / "canonical_accepted.jsonl"
    shutil.copyfile(args.accepted, canonical_path)
    write_jsonl(args.output_dir / "llm_finetune.jsonl", llm_rows(rows, args.language))
    rel_rows = relation_rows(rows)
    ner_rows = ner_char_rows(rows)
    write_jsonl(args.output_dir / "relation_extraction.jsonl", rel_rows)
    write_jsonl(args.output_dir / "ner_spans.jsonl", ner_rows)
    write_readme(args.output_dir, {"accepted": len(rows), "relations": len(rel_rows), "ner": len(ner_rows)}, args.language)
    print(f"Wrote training data to {args.output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
